# Generated by Django 4.0.3 on 2022-04-11 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoGameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BingoRoom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bingo_price', models.IntegerField()),
                ('auction_start_price', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField(null=True)),
                ('winned_bid', models.IntegerField(null=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BingoRoomAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_auction_id', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('start_price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('coin_per_bid', models.IntegerField()),
                ('price_per_bid', models.DecimalField(decimal_places=5, max_digits=8)),
                ('live', models.BooleanField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroom')),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoinBuyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('wallet_address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BingoRoomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_eth', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField(null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroom')),
            ],
        ),
        migrations.CreateModel(
            name='BingoRoomAuctionBidHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bid_id_of_auction', models.IntegerField()),
                ('bid_price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('bid_time', models.DateTimeField()),
                ('win_state', models.BooleanField()),
                ('bidder', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('room_auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroomauction')),
            ],
        ),
        migrations.CreateModel(
            name='BingoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_numbers', models.CharField(default='', max_length=200)),
                ('last_number', models.IntegerField(blank=True, default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_cards_count', models.IntegerField()),
                ('live', models.BooleanField(default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroom')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='game.bingogamestatus')),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BingoBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField()),
                ('card_info', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField()),
                ('winning_state', models.BooleanField(default=False)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.bingogame')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
