# Generated by Django 3.2.13 on 2022-04-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bingobids',
            old_name='date',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='bingogame',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='bingogame',
            old_name='start_date',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='bingoroom',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='bingoroom',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bingoroom',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='bingoroom',
            name='winned_bid',
        ),
        migrations.AddField(
            model_name='bingogame',
            name='elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bingoroom',
            name='hold_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bingoroomhistory',
            name='winned_bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bingogame',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bingogame',
            name='total_cards_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bingogame',
            name='winner',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
