# Generated by Django 3.2.13 on 2022-04-14 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20220413_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingobids',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.bingogame'),
        ),
        migrations.AlterField(
            model_name='bingobids',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bingogame',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroom'),
        ),
        migrations.AlterField(
            model_name='bingogame',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bingoroomauction',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroom'),
        ),
        migrations.AlterField(
            model_name='bingoroomauction',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bingoroomauctionbidhistory',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bingoroomauctionbidhistory',
            name='room_auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroomauction'),
        ),
        migrations.AlterField(
            model_name='bingoroomhistory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bingoroomhistory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroom'),
        ),
        migrations.AlterField(
            model_name='usercoinbuyhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
