# Generated by Django 3.2.13 on 2022-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_userprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingogame',
            name='status',
            field=models.CharField(choices=[('S', 'selling'), ('C', 'calling'), ('T', 'transition'), ('E', 'ended')], default='S', max_length=50),
        ),
    ]
