# Generated by Django 3.2.13 on 2022-04-16 07:15

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_alter_bingogame_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingoroom',
            name='auction_start_price',
        ),
        migrations.RemoveField(
            model_name='bingoroomauction',
            name='room_auction_id',
        ),
        migrations.AddField(
            model_name='bingobids',
            name='match_state',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=27), default=[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], size=6),
        ),
        migrations.AddField(
            model_name='bingoroomauction',
            name='last_bid_elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bingoroomauction',
            name='time_limit',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='bingoroomhistory',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='game.bingoroomauction'),
        ),
        migrations.AddField(
            model_name='bingoroomhistory',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_wallet',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bingobids',
            name='card_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=162),
        ),
        migrations.AlterField(
            model_name='bingoroomauction',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bingoroomauction',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bingoroomhistory',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bingoroomhistory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.bingoroom'),
        ),
        migrations.AlterField(
            model_name='bingoroomhistory',
            name='winned_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.bingoroomauctionbidhistory'),
        ),
        migrations.CreateModel(
            name='BingoRoomSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_attendee_count', models.IntegerField(default=10)),
                ('selling_time', models.IntegerField(default=600, validators=[django.core.validators.MaxValueValidator(1800), django.core.validators.MinValueValidator(180)], verbose_name='ticket selling time(s)')),
                ('calling_time', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(5)], verbose_name='number calling time(s)')),
                ('auction_start_price', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('auction_price_interval_per_bid', models.DecimalField(decimal_places=5, max_digits=8)),
                ('auction_coin_per_bid', models.IntegerField(default=10)),
                ('auction_win_time_limit', models.IntegerField(default=3600)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.bingoroom')),
            ],
        ),
    ]
