# Generated by Django 3.2.13 on 2022-04-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20220416_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingoroomhistory',
            name='winned_bid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='game.bingoroomauctionbidhistory'),
        ),
    ]
