# Generated by Django 3.2.13 on 2022-04-16 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_bingoroomhistory_winned_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingobids',
            name='match_state',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=27), default=None, size=6),
        ),
    ]
