# Generated by Django 3.2.13 on 2022-04-18 06:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20220417_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingogame',
            name='called_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
