# Generated by Django 3.2.13 on 2022-04-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_bingogame_called_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
    ]
