# Generated by Django 3.2.13 on 2022-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingoroomauctionbidhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
