# Generated by Django 3.2.13 on 2022-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_bingoroom_owner_room_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingobids',
            name='earning',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=8),
        ),
    ]
