# Generated by Django 3.2.13 on 2022-06-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0016_bingobids_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='earning_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=0)),
                ('game_kind', models.CharField(choices=[('B', 'bingo')], default='B', max_length=255)),
                ('is_owner', models.BooleanField(default=False)),
                ('earning', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
