# Generated by Django 3.2.13 on 2022-06-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20220614_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userearnings',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bingoroomhistory',
            name='winned_bid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.bingoroomauctionbidhistory'),
        ),
    ]
