# Generated by Django 3.2.13 on 2022-07-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20220702_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingoroomauction',
            name='pay_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
