# Generated by Django 4.0.3 on 2022-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_first_name_user_last_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referer',
            field=models.CharField(blank=True, max_length=30, verbose_name='referer username'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=2048, verbose_name='wallet address'),
        ),
    ]
