# Generated by Django 3.2.13 on 2022-04-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_referer_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='black_user',
            field=models.BooleanField(default=False),
        ),
    ]
